server:
  port: 8002

spring:
  application:
    name: user-service

  config:
    #    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.192.2:30088} # VPN
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-service:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
