apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      nodePort: 30082
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: default
      initContainers:
        - name: wait-for-config
          image: curlimages/curl:8.7.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for config-service...";
              until curl -s http://config-service:8888/actuator/health | grep '"status":"UP"' > /dev/null; do
                echo "Config-service not ready yet. Waiting...";
                sleep 3;
              done
              echo "Config-service is UP.";

        - name: wait-for-database
          image: busybox:1.36.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for DB (192.168.1.31:3308)...";
              until nc -z 192.168.1.31 3308; do
                echo "DB not ready yet. Waiting...";
                sleep 3;
              done
              echo "DB is reachable.";

        - name: wait-for-minio
          image: busybox:1.36.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for minIO (192.168.1.31:9000)...";
              until nc -z 192.168.1.31 9000; do
                echo "minIO not ready yet. Waiting...";
                sleep 3;
              done
              echo "minIO is reachable.";

      containers:
        - name: user-service
          image: lhdmir/user-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-service:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
